compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-11"

[[durable_objects.bindings]]
name = "$DurableObject"
class_name = "$DurableObject"

[[migrations]]
tag = "v1"
new_classes = [ "$DurableObject" ]
