blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Akryum/rstore/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  # - name: Discord Chat
  #   url: https://discord.gg/xxxxx
  #   about: Ask questions and discuss with other rstore users in real time.
