name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - run: corepack enable
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:types
      - run: pnpm test
